name: CI

on:
    push:
        branches:
            - main
            - '[0-9]+.[0-9]+'
    pull_request: ~

jobs:
    cs-fix:
        name: Run code style check
        runs-on: "ubuntu-20.04"
        strategy:
            matrix:
                php:
                    - '8.0'
        steps:
            - uses: hmarr/debug-action@v2
            - name: Save PR number
              env:
                  PR_NUMBER: ${{ github.event.number }}
              run: |
                  mkdir -p ./coverage
                  echo "test" > ./coverage/coverage-tests.xml
            - uses: actions/upload-artifact@v3
              with:
                  name: code-coverage-report
                  path: coverage/
