name: SonarCloud CI Analysis
on:
    workflow_run:
        workflows:
            - "CI"
        types:
            - completed
jobs:
    sonarcloud:
        name: SonarCloud
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - uses: hmarr/debug-action@v2

            - name: Download Artifacts
              uses: dawidd6/action-download-artifact@v2
              with:
                  workflow: ci.yaml
                  name: code-coverage
            - name: Load PR number
              run: |
                  ls -la
                  cat pr_number
                  echo "PR_NUMBER=$(cat pr_number)" >> $GITHUB_ENV
            - name: Add Coverage PR Comment
              if: "contains(github.event.workflow_run.event, 'pull_request')"
              uses: marocchino/sticky-pull-request-comment@v2
              with:
                  number: ${{ env.PR_NUMBER }}
                  recreate: true
                  message: |
                      Hello, world!
